metadata:
  description: >-
    Sample community config
user:
  RUN_ENVIR: community
  MACHINE: orion
  ACCOUNT: ufs-phys
platform:
  #MODEL: FV3_RRFS_v1beta_CONUS_3km
  MODEL: FV3_HRRR_CONUS_3km
  MET_INSTALL_DIR: ""
  METPLUS_PATH: ""
  CCPA_OBS_DIR: ""
  MRMS_OBS_DIR: ""
  NDAS_OBS_DIR: ""
workflow:
  EXPT_SUBDIR: HRRR_3km_65L_warm
  CCPP_PHYS_SUITE: FV3_HRRR
  DATE_FIRST_CYCL: '2019041500'
  DATE_LAST_CYCL: '2019053000'
  FCST_LEN_HRS: 36 
  INCR_CYCL_FREQ: 72
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: true
  COMPILER: intel
workflow_switches:
  RUN_TASK_MAKE_GRID: true
  RUN_TASK_MAKE_OROG: true
  RUN_TASK_MAKE_SFC_CLIMO: true
  RUN_TASK_GET_OBS_CCPA: false
  RUN_TASK_GET_OBS_MRMS: false
  RUN_TASK_GET_OBS_NDAS: false
  RUN_TASK_VX_GRIDSTAT: false
  RUN_TASK_VX_POINTSTAT: false
  RUN_TASK_VX_ENSGRID: false
  RUN_TASK_VX_ENSPOINT: false
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: FV3GFS
  FV3GFS_FILE_FMT_ICS: nemsio 
#zhang
  USE_USER_STAGED_EXTRN_FILES: true
  EXTRN_MDL_SOURCE_BASEDIR_ICS: "/work/noaa/fv3-cam/ekalina/gfs_grib2_combine"
  EXTRN_MDL_FILES_ICS: "gfs.t00z.atmanl.nemsio  gfs.t00z.sfcanl.nemsio"
task_get_extrn_lbcs:
  EXTRN_MDL_NAME_LBCS: FV3GFS
  LBC_SPEC_INTVL_HRS: 3
  FV3GFS_FILE_FMT_LBCS: grib2
#zhang
  USE_USER_STAGED_EXTRN_FILES: true
  EXTRN_MDL_SOURCE_BASEDIR_LBCS: "/work/noaa/fv3-cam/ekalina/gfs_grib2_combine"
  EXTRN_MDL_FILES_LBCS: "gfs.t00z.pgrb2.0p25.f003 gfs.t00z.pgrb2.0p25.f006 gfs.t00z.pgrb2.0p25.f009 gfs.t00z.pgrb2.0p25.f012 gfs.t00z.pgrb2.0p25.f015 gfs.t00z.pgrb2.0p25.f018 gfs.t00z.pgrb2.0p25.f021 gfs.t00z.pgrb2.0p25.f024 gfs.t00z.pgrb2.0p25.f027 gfs.t00z.pgrb2.0p25.f030 gfs.t00z.pgrb2.0p25.f033 gfs.t00z.pgrb2.0p25.f036 gfs.t00z.pgrb2.0p25.f039 gfs.t00z.pgrb2.0p25.f042 gfs.t00z.pgrb2.0p25.f045 gfs.t00z.pgrb2.0p25.f048 gfs.t00z.pgrb2.0p25.f051 gfs.t00z.pgrb2.0p25.f054 gfs.t00z.pgrb2.0p25.f057 gfs.t00z.pgrb2.0p25.f060"

task_run_fcst:
  WTIME_RUN_FCST: 07:59:00
  QUILTING: true
  PREDEF_GRID_NAME: RRFS_CONUS_3km
global:
  DO_ENSEMBLE: false
  NUM_ENS_MEMBERS: 2
